apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: website
            port: 
              number: 3000
        pathType: Prefix
      - path: /api
        backend:
          service:
            name: api
            port:
              number: 80
        pathType: Prefix
